apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mysql
    role: storage
    tier: backend
  name: mysql
spec:
  replicas: 1
  selector:
    name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - command:
        - mysql-proxy
        - --proxy-backend-addresses=$(MYSQL_HOST)
        - --plugins=proxy
        - --proxy-address=0.0.0.0:3306
        - --proxy-lua-script=/profiler.lua
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              key: host
              name: mysql-config
        image: 944590742144.dkr.ecr.eu-west-1.amazonaws.com/apply/smart-mysql-proxy:build-11
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30M
      imagePullSecrets:
      - name: registry-key
      nodeSelector:
        beta.kubernetes.io/instance-type: t2.medium
